version: '3.8'

stages:
  - name: "Deploy CVSS System"
    steps:
      - name: "Install and Deploy"
        action: "shell"
        inputs:
          script: |
            #!/bin/bash
            set -e
            
            echo "Starting CVSS System deployment..."
            
            # Update system
            yum update -y
            
            # Install Python 3.12
            yum install -y epel-release
            yum install -y python3.12 python3.12-pip python3.12-devel
            ln -sf /usr/bin/python3.12 /usr/bin/python3
            
            # Install Node.js 18
            curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
            yum install -y nodejs
            
            # Install PostgreSQL
            yum install -y postgresql postgresql-server postgresql-devel
            postgresql-setup initdb
            systemctl start postgresql
            systemctl enable postgresql
            
            # Create database
            sudo -u postgres psql -c "CREATE DATABASE cvss_db;"
            sudo -u postgres psql -c "CREATE USER cvss_user WITH PASSWORD 'cvss_password';"
            sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE cvss_db TO cvss_user;"
            
            # Install build tools
            yum groupinstall -y "Development Tools"
            yum install -y git curl wget unzip gcc gcc-c++ make
            
            # Create application user
            useradd -r -s /bin/bash -d /opt/cvss-system cvss || true
            
            # Setup directories
            mkdir -p /opt/cvss-system
            mkdir -p /var/log/cvss-system
            chown -R cvss:cvss /opt/cvss-system
            chown -R cvss:cvss /var/log/cvss-system
            
            # Copy application files
            cp -r backend /opt/cvss-system/
            cp -r frontend /opt/cvss-system/
            chown -R cvss:cvss /opt/cvss-system
            
            # Setup backend
            cd /opt/cvss-system/backend
            sudo -u cvss python3 -m venv venv
            sudo -u cvss ./venv/bin/pip install --upgrade pip
            sudo -u cvss ./venv/bin/pip install -r requirements.txt
            
            # Create backend .env file
            echo "DATABASE_URL=postgresql://cvss_user:cvss_password@localhost:5432/cvss_db" > .env
            echo "SQLALCHEMY_DATABASE_URI=postgresql://cvss_user:cvss_password@localhost:5432/cvss_db" >> .env
            echo "JWT_SECRET_KEY=your-production-jwt-secret-key-here" >> .env
            echo "FLASK_ENV=production" >> .env
            echo "FLASK_DEBUG=False" >> .env
            echo "SECRET_KEY=your-production-secret-key-here" >> .env
            echo "CORS_ORIGINS=http://0.0.0.0:5000" >> .env
            echo "MAX_CONTENT_LENGTH=16777216" >> .env
            echo "UPLOAD_FOLDER=uploads" >> .env
            echo "API_VERSION=v1" >> .env
            
            chown cvss:cvss .env
            
            # Initialize database
            sudo -u cvss ./venv/bin/python init_db.py
            
            # Setup frontend
            cd /opt/cvss-system/frontend
            sudo -u cvss npm ci
            
            # Create frontend .env file
            echo "VITE_API_URL=http://0.0.0.0:5000/api" > .env
            echo "VITE_APP_NAME=CVSS Scoring System" >> .env
            echo "VITE_APP_VERSION=1.0.0" >> .env
            echo "VITE_DEV_MODE=false" >> .env
            
            chown cvss:cvss .env
            
            # Build application
            sudo -u cvss npm run build
            
            # Create backend systemd service
            cat > /etc/systemd/system/cvss-backend.service << EOF
            [Unit]
            Description=CVSS System Backend
            After=network.target postgresql.service
            
            [Service]
            Type=simple
            User=cvss
            WorkingDirectory=/opt/cvss-system/backend
            Environment=PATH=/opt/cvss-system/backend/venv/bin
            ExecStart=/opt/cvss-system/backend/venv/bin/python run.py
            Restart=always
            RestartSec=10
            StandardOutput=append:/var/log/cvss-system/backend.log
            StandardError=append:/var/log/cvss-system/backend-error.log
            
            [Install]
            WantedBy=multi-user.target
            EOF
            
            # Create frontend systemd service
            cat > /etc/systemd/system/cvss-frontend.service << EOF
            [Unit]
            Description=CVSS System Frontend
            After=network.target cvss-backend.service
            
            [Service]
            Type=simple
            User=cvss
            WorkingDirectory=/opt/cvss-system/frontend
            Environment=PATH=/usr/bin:/usr/local/bin
            ExecStart=/usr/bin/npm run dev
            Restart=always
            RestartSec=10
            StandardOutput=append:/var/log/cvss-system/frontend.log
            StandardError=append:/var/log/cvss-system/frontend-error.log
            
            [Install]
            WantedBy=multi-user.target
            EOF
            
            # Reload systemd
            systemctl daemon-reload
            
            # Configure firewall
            yum install -y firewalld
            systemctl start firewalld
            systemctl enable firewalld
            firewall-cmd --permanent --add-port=5000/tcp
            firewall-cmd --permanent --add-port=3000/tcp
            firewall-cmd --permanent --add-port=22/tcp
            firewall-cmd --permanent --add-port=80/tcp
            firewall-cmd --permanent --add-port=443/tcp
            firewall-cmd --reload
            
            # Start services
            systemctl start cvss-backend
            systemctl enable cvss-backend
            systemctl start cvss-frontend
            systemctl enable cvss-frontend
            
            # Wait and check services
            sleep 30
            
            echo "Checking service status..."
            systemctl status cvss-backend --no-pager
            systemctl status cvss-frontend --no-pager
            
            echo "CVSS System deployed successfully!"
            echo "Backend: http://localhost:5000"
            echo "Frontend: http://localhost:3000"
